import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  mainSidebar: [
    {
      type: "category",
      label: "Get Started",
      collapsed: false,
      items: [
        "get-started/index",
        "get-started/installation",
        "get-started/first-agent",
        "get-started/connect-client",
      ],
    },
    {
      type: "category",
      label: "Beginner Path",
      collapsed: true,
      items: [
        "beginner/index",
        "beginner/mental-model",
        "beginner/your-first-agent",
        "beginner/add-a-tool",
        "beginner/add-memory",
        "beginner/run-with-api",
        "beginner/test-with-playground",
        "beginner/call-from-typescript",
      ],
    },
    {
      type: "category",
      label: "Concepts",
      collapsed: true,
      items: [
        "concept2/index",
        "concept2/agents-tools-control",
        "concept2/memory",
        "concept2/serving-agents",
        "concept2/connecting-clients",
        "concept2/extensibility",
        "concept2/qa",
      ],
    },
    {
      type: "category",
      label: "Concepts in Depth",
      collapsed: true,
      items: [
        "concepts/architecture",
        "concepts/state-graph",
        "concepts/agents-and-tools",
        "concepts/state-and-messages",
        "concepts/streaming",
        "concepts/prebuilt-agents-and-tools",
        "concepts/checkpointing-and-threads",
        "concepts/remote-tools",
        "concepts/memory-and-store",
        "concepts/media-and-files",
        "concepts/dependency-injection",
        "concepts/callbacks-and-command",
        "concepts/security-and-validators",
        "concepts/context-id-background",
        "concepts/providers-and-adapters",
        "concepts/publishers-and-runtime-protocols",
        "concepts/testing-and-evaluation",
        "concepts/production-runtime",
      ],
    },
    {
      type: "category",
      label: "Prebuilt",
      collapsed: true,
      items: [
        {
          type: "category",
          label: "Agents",
          items: [
            "prebuild/agents/react-agent",
            "prebuild/agents/plan-act-reflect-agent",
            "prebuild/agents/swarm-agent",
            "prebuild/agents/supervisor-team-agent",
            "prebuild/agents/rag-agent",
            "prebuild/agents/structured-output-agent",
            "prebuild/agents/audio-agent",
          ],
        },
        {
          type: "category",
          label: "Tools",
          items: [
            "prebuild/tools/web-tools",
            "prebuild/tools/file-tools",
            "prebuild/tools/memory-tools",
            "prebuild/tools/calculator",
            "prebuild/tools/handoff",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "How-to guides",
      collapsed: true,
      items: [
        
        {
          type: "category",
          label: "Python Library",
          items: [
            "how-to/python/build-a-graph",
            "how-to/python/configure-agent",
            "how-to/python/use-tool-decorator",
            "how-to/python/use-custom-state",
            "how-to/python/set-up-checkpointing",
            "how-to/python/stream-graph",
            "how-to/python/use-custom-nodes",
            "how-to/python/choose-the-right-abstraction",
            "how-to/python/use-memory-store",
            "how-to/python/use-prebuilt-agents",
            "how-to/python/use-prebuilt-tools",
            "how-to/python/use-publishers",
            "how-to/python/send-traces-to-logfire-langsmith",
            "how-to/python/use-dependency-injection",
            "how-to/python/use-mcp",
            "how-to/python/use-context-manager",
            "how-to/python/protect-against-prompt-injection",
            "how-to/python/emit-tool-progress",
            "how-to/python/run-background-tasks",
            "how-to/python/configure-id-generator",
            "how-to/python/handoff-between-agents",
            "how-to/python/use-realtime-audio",
          ],
        },
        {
          type: "category",
          label: "Production",
          items: [
            "how-to/production/index",
            "how-to/production/api-reference",
            "how-to/production/agentflow-json",
            "how-to/production/environment-variables",
            "how-to/production/auth-and-authorization",
            "how-to/production/checkpointing",
            "how-to/production/multimodal-and-vision",
            "how-to/production/logging-and-metrics",
            "how-to/production/deployment",
            "how-to/production/troubleshooting",
          ],
        },
        {
          type: "category",
          label: "CLI",
          items: [
            "how-to/api-cli/index",
            "how-to/api-cli/initialize-project",
            "how-to/api-cli/run-api-server",
            "how-to/api-cli/open-playground",
            "how-to/api-cli/configure-agentflow-json",
            "how-to/api-cli/add-auth",
            "how-to/api-cli/configure-rate-limiting",
            "how-to/api-cli/generate-docker-files",
            "how-to/api-cli/install-skills",
            "how-to/api-cli/run-tests",
            "how-to/api-cli/run-evals",
          ],
        },
        {
          type: "category",
          label: "TypeScript Client",
          items: [
            "how-to/client/create-client",
            "how-to/client/invoke-agent",
            "how-to/client/stream-responses",
            "how-to/client/manage-threads",
            "how-to/client/use-memory-api",
            "how-to/client/upload-files",
            "how-to/client/send-images-and-documents",
            "how-to/client/realtime-audio",
            "how-to/client/register-remote-tools",
            "how-to/client/graph-utilities",
          ],
        },
      ],
    },

    {
      type: "category",
      label: "Testing & QA",
      collapsed: true,
      items: [
        "qa/index",
        {
          type: "category",
          label: "Unit Testing",
          items: [
            "qa/unit-test/index",
          ],
        },
        {
          type: "category",
          label: "Evaluation",
          items: [
            "qa/evaluation/index",
            "qa/evaluation/eval-set",
            "qa/evaluation/criteria",
            "qa/evaluation/presets",
            "qa/evaluation/reports",
            "qa/evaluation/user-simulation",
          ],
        },
      ],
    },

    {
      type: "category",
      label: "Glossary",
      collapsed: true,
      items: [
        "glossary/index",
        "glossary/what-is-an-ai-agent",
        "glossary/what-is-a-react-agent",
        "glossary/what-is-multi-agent-orchestration",
        "glossary/what-is-a-state-graph",
        "glossary/what-is-agent-memory",
        "glossary/what-is-model-context-protocol",
        "glossary/what-is-retrieval-augmented-generation",
        "glossary/what-is-agent-streaming",
      ],
    },
    {
      type: "category",
      label: "Compare",
      collapsed: true,
      items: [
        "compare/index",
        "compare/agentflow-vs-langgraph",
        "compare/agentflow-vs-crewai",
        "compare/agentflow-vs-autogen",
        "compare/agentflow-vs-llamaindex-agents",
        "compare/agentflow-vs-google-adk",
        "compare/best-python-agent-framework-2026",
      ],
    }, 
    
    {
      type: "category",
      label: "Providers",
      collapsed: true,
      items: [
        "providers/index",
        "providers/openai",
        "providers/google",
      ],
    },
    {
      type: "category",
      label: "Skills",
      collapsed: true,
      items: [
        "skills/index",
      ],
    },
    {
      type: "category",
      label: "Integrations",
      collapsed: true,
      items: [
        "integrations/index",
        "integrations/agentflow-with-fastapi",
        "integrations/agentflow-with-nextjs",
        "integrations/agentflow-with-postgres",
      ],
    },
    {
      type: "category",
      label: "Use Cases",
      collapsed: true,
      items: [
        "use-cases/index",
        "use-cases/customer-support-agent",
        "use-cases/data-extraction-agent",
        "use-cases/coding-agent",
        "use-cases/research-agent",
        "use-cases/rag-agent",
      ],
    },
    {
      type: "category",
      label: "Tutorials",
      collapsed: true,
      items: [
        "tutorials/index",
        {
          type: "category",
          label: "From Examples",
          items: [
            "tutorials/from-examples/agent-class",
            "tutorials/from-examples/custom-state",
            "tutorials/from-examples/google-genai",
            "tutorials/from-examples/tool-decorator",
            "tutorials/from-examples/react-agent",
            "tutorials/from-examples/react-agent-validation",
            "tutorials/from-examples/react-streaming",
            "tutorials/from-examples/stream-sync",
            "tutorials/from-examples/stop-stream",
            "tutorials/from-examples/dependency-injection",
            "tutorials/from-examples/mcp-server",
            "tutorials/from-examples/mcp-client",
            "tutorials/from-examples/mcp-react-agent",
            "tutorials/from-examples/github-mcp",
            "tutorials/from-examples/mcp-file-download",
            "tutorials/from-examples/memory",
            "tutorials/from-examples/qdrant-memory",
            "tutorials/from-examples/multimodal",
            "tutorials/from-examples/multiagent",
            "tutorials/from-examples/handoff",
            "tutorials/from-examples/skills",
            "tutorials/from-examples/skills-chat",
            "tutorials/from-examples/testing",
            "tutorials/from-examples/evaluation",
            "tutorials/from-examples/graceful-shutdown",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "GenAI Courses",
      collapsed: true,
      items: [
        "courses/index",
        {
          type: "category",
          label: "Shared Foundations",
          collapsed: true,
          items: [
            "courses/shared/index",
            "courses/shared/glossary",
            "courses/shared/llm-basics-for-engineers",
            "courses/shared/transformer-basics",
            "courses/shared/tokenization-and-context-windows",
            "courses/shared/embeddings-vectorization-and-similarity",
            "courses/shared/chunking-and-retrieval-primitives",
            "courses/shared/prompt-and-output-patterns-cheatsheet",
            "courses/shared/design-checklists",
            "courses/shared/evaluation-worksheet",
            "courses/shared/release-checklist",
          ],
        },
        {
          type: "category",
          label: "GenAI Beginner",
          collapsed: true,
          items: [
            "courses/genai-beginner/index",
            "courses/genai-beginner/lesson-1-use-cases-models-and-app-lifecycle",
            "courses/genai-beginner/lesson-2-prompting-context-and-structured-outputs",
            "courses/genai-beginner/lesson-3-tools-files-and-mcp-basics",
            "courses/genai-beginner/lesson-4-retrieval-grounding-and-citations",
            "courses/genai-beginner/lesson-5-state-memory-threads-and-streaming",
            "courses/genai-beginner/lesson-6-multimodal-and-client-server-integration",
            "courses/genai-beginner/lesson-7-evals-safety-cost-and-release",
            "courses/genai-beginner/capstone",
          ],
        },
        {
          type: "category",
          label: "GenAI Advanced",
          collapsed: true,
          items: [
            "courses/genai-advanced/index",
            "courses/genai-advanced/lesson-1-agentic-product-fit-and-system-bounded-autonomy",
            "courses/genai-advanced/lesson-2-single-agent-runtime-and-bounded-autonomy",
            "courses/genai-advanced/lesson-3-context-engineering-long-context-and-caching",
            "courses/genai-advanced/lesson-4-knowledge-systems-and-advanced-rag",
            "courses/genai-advanced/lesson-5-router-manager-and-specialist-patterns",
            "courses/genai-advanced/lesson-6-handoffs-human-review-and-control-surfaces",
            "courses/genai-advanced/lesson-7-memory-checkpoints-artifacts-and-durable-execution",
            "courses/genai-advanced/lesson-8-observability-testing-security-and-deployment",
            "courses/genai-advanced/architecture-review-exercise",
          ],
        },
      ],
    },

    {
      type: "category",
      label: "Troubleshooting",
      collapsed: true,
      items: [
        "troubleshooting/installation",
        "troubleshooting/api-server",
        "troubleshooting/client",
        "troubleshooting/playground",
        "troubleshooting/error-codes",
        "troubleshooting/error-patterns",
      ],
    },
    {
      type: "category",
      label: "Reference",
      collapsed: true,
      items: [
        {
          type: "category",
          label: "API & CLI",
          items: [
            "reference/api-cli/commands",
            "reference/api-cli/configuration",
            "reference/api-cli/auth",
            "reference/api-cli/rate-limiting",
            "reference/api-cli/environment",
            "reference/api-cli/thread-name-generator",
            "reference/api-cli/id-generator",
          ],
        },
        {
          type: "category",
          label: "REST API",
          items: [
            "reference/rest-api/graph",
            "reference/rest-api/live",
            "reference/rest-api/threads",
            "reference/rest-api/memory-store",
            "reference/rest-api/files",
            "reference/rest-api/observability",
            "reference/rest-api/evals",
            "reference/rest-api/ping",
          ],
        },
        {
          type: "category",
          label: "TypeScript Client",
          items: [
            "reference/client/agentflow-client",
            "reference/client/graph",
            "reference/client/message",
            "reference/client/invoke",
            "reference/client/stream",
            "reference/client/realtime",
            "reference/client/threads",
            "reference/client/memory",
            "reference/client/files",
            "reference/client/auth",
            "reference/client/tools",
          ],
        },
        {
          type: "category",
          label: "Python Library",
          items: [
            "reference/python/graph",
            "reference/python/agent",
            "reference/python/llm",
            "reference/python/skills",
            "reference/python/state",
            "reference/python/messages",
            "reference/python/tools",
            "reference/python/stream-emitter",
            "reference/python/checkpointers",
            "reference/python/memory-stores",
            "reference/python/media",
            "reference/python/publishers",
            "reference/python/realtime",
            "reference/python/testing",
            "reference/python/evaluation",
            "reference/python/context-manager",
            "reference/python/callback-manager",
            "reference/python/lifecycle-callbacks",
            "reference/python/background-tasks",
            "reference/python/id-generator",
            "reference/python/command-handoff",
          ],
        },
      ],
    },
  ],
};

export default sidebars;